plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-70
  stylelint:
    enabled: true
